// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.gmvpn_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_gmvpn_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_gmvpn_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "gmvpn_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "gmvpn_ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_gmvpn_ffi_checksum_func_build_xray_config(
    ): Short
    external fun uniffi_gmvpn_ffi_checksum_func_core_version(
    ): Short
    external fun uniffi_gmvpn_ffi_checksum_func_decode_subscription(
    ): Short
    external fun uniffi_gmvpn_ffi_checksum_func_decode_subscription_uris(
    ): Short
    external fun uniffi_gmvpn_ffi_checksum_func_default_tunnel_options(
    ): Short
    external fun uniffi_gmvpn_ffi_checksum_func_parse_profile_uri(
    ): Short
    external fun ffi_gmvpn_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "gmvpn_ffi"))
        
    }
    external fun uniffi_gmvpn_ffi_fn_func_build_xray_config(`profile`: RustBuffer.ByValue,`options`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_gmvpn_ffi_fn_func_core_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_gmvpn_ffi_fn_func_decode_subscription(`body`: RustBuffer.ByValue,`format`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_gmvpn_ffi_fn_func_decode_subscription_uris(`body`: RustBuffer.ByValue,`format`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_gmvpn_ffi_fn_func_default_tunnel_options(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_gmvpn_ffi_fn_func_parse_profile_uri(`uri`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_gmvpn_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_gmvpn_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_gmvpn_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_gmvpn_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_gmvpn_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_gmvpn_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_gmvpn_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_gmvpn_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_gmvpn_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_gmvpn_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_gmvpn_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_gmvpn_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_gmvpn_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_gmvpn_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_gmvpn_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_gmvpn_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_gmvpn_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_gmvpn_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_gmvpn_ffi_checksum_func_build_xray_config() != 6243.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_gmvpn_ffi_checksum_func_core_version() != 63946.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_gmvpn_ffi_checksum_func_decode_subscription() != 3680.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_gmvpn_ffi_checksum_func_decode_subscription_uris() != 53759.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_gmvpn_ffi_checksum_func_default_tunnel_options() != 51799.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_gmvpn_ffi_checksum_func_parse_profile_uri() != 13394.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Output of a successful `decode_subscription` call.
 */
data class FfiDecodeOutput (
    var `profiles`: List<FfiProfile>
    , 
    var `warnings`: List<FfiDecodeWarning>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiDecodeOutput: FfiConverterRustBuffer<FfiDecodeOutput> {
    override fun read(buf: ByteBuffer): FfiDecodeOutput {
        return FfiDecodeOutput(
            FfiConverterSequenceTypeFfiProfile.read(buf),
            FfiConverterSequenceTypeFfiDecodeWarning.read(buf),
        )
    }

    override fun allocationSize(value: FfiDecodeOutput) = (
            FfiConverterSequenceTypeFfiProfile.allocationSize(value.`profiles`) +
            FfiConverterSequenceTypeFfiDecodeWarning.allocationSize(value.`warnings`)
    )

    override fun write(value: FfiDecodeOutput, buf: ByteBuffer) {
            FfiConverterSequenceTypeFfiProfile.write(value.`profiles`, buf)
            FfiConverterSequenceTypeFfiDecodeWarning.write(value.`warnings`, buf)
    }
}



/**
 * Per-entry failure recorded while decoding a subscription.
 */
data class FfiDecodeWarning (
    /**
     * Zero-based line or element index.
     */
    var `index`: kotlin.UInt
    , 
    /**
     * Offending input, trimmed.
     */
    var `input`: kotlin.String
    , 
    /**
     * Human-readable reason.
     */
    var `reason`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiDecodeWarning: FfiConverterRustBuffer<FfiDecodeWarning> {
    override fun read(buf: ByteBuffer): FfiDecodeWarning {
        return FfiDecodeWarning(
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiDecodeWarning) = (
            FfiConverterUInt.allocationSize(value.`index`) +
            FfiConverterString.allocationSize(value.`input`) +
            FfiConverterString.allocationSize(value.`reason`)
    )

    override fun write(value: FfiDecodeWarning, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`index`, buf)
            FfiConverterString.write(value.`input`, buf)
            FfiConverterString.write(value.`reason`, buf)
    }
}



/**
 * One server profile. Matches `schemas/profile.schema.json` (the JSON
 * shape is still available for storage — this is the live in-memory
 * type clients work with).
 */
data class FfiProfile (
    /**
     * Stable client-side UUID (v4).
     */
    var `id`: kotlin.String
    , 
    var `name`: kotlin.String
    , 
    var `remark`: kotlin.String?
    , 
    var `protocol`: FfiProtocol
    , 
    var `server`: kotlin.String
    , 
    var `port`: kotlin.UShort
    , 
    var `auth`: FfiAuth
    , 
    var `transport`: FfiTransport
    , 
    var `security`: FfiSecurity
    , 
    var `tags`: List<kotlin.String>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiProfile: FfiConverterRustBuffer<FfiProfile> {
    override fun read(buf: ByteBuffer): FfiProfile {
        return FfiProfile(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterTypeFfiProtocol.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterTypeFfiAuth.read(buf),
            FfiConverterTypeFfiTransport.read(buf),
            FfiConverterTypeFfiSecurity.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: FfiProfile) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`remark`) +
            FfiConverterTypeFfiProtocol.allocationSize(value.`protocol`) +
            FfiConverterString.allocationSize(value.`server`) +
            FfiConverterUShort.allocationSize(value.`port`) +
            FfiConverterTypeFfiAuth.allocationSize(value.`auth`) +
            FfiConverterTypeFfiTransport.allocationSize(value.`transport`) +
            FfiConverterTypeFfiSecurity.allocationSize(value.`security`) +
            FfiConverterSequenceString.allocationSize(value.`tags`)
    )

    override fun write(value: FfiProfile, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`remark`, buf)
            FfiConverterTypeFfiProtocol.write(value.`protocol`, buf)
            FfiConverterString.write(value.`server`, buf)
            FfiConverterUShort.write(value.`port`, buf)
            FfiConverterTypeFfiAuth.write(value.`auth`, buf)
            FfiConverterTypeFfiTransport.write(value.`transport`, buf)
            FfiConverterTypeFfiSecurity.write(value.`security`, buf)
            FfiConverterSequenceString.write(value.`tags`, buf)
    }
}



/**
 * Reality-specific fields. Only present when `FfiSecurity.mode == Reality`.
 */
data class FfiRealityConfig (
    var `publicKey`: kotlin.String
    , 
    var `shortId`: kotlin.String
    , 
    var `spiderX`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiRealityConfig: FfiConverterRustBuffer<FfiRealityConfig> {
    override fun read(buf: ByteBuffer): FfiRealityConfig {
        return FfiRealityConfig(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiRealityConfig) = (
            FfiConverterString.allocationSize(value.`publicKey`) +
            FfiConverterString.allocationSize(value.`shortId`) +
            FfiConverterOptionalString.allocationSize(value.`spiderX`)
    )

    override fun write(value: FfiRealityConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`publicKey`, buf)
            FfiConverterString.write(value.`shortId`, buf)
            FfiConverterOptionalString.write(value.`spiderX`, buf)
    }
}



/**
 * TLS / Reality parameters.
 */
data class FfiSecurity (
    var `mode`: FfiSecurityMode
    , 
    var `sni`: kotlin.String?
    , 
    var `alpn`: List<kotlin.String>
    , 
    var `allowInsecure`: kotlin.Boolean
    , 
    var `fingerprint`: kotlin.String?
    , 
    var `reality`: FfiRealityConfig?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiSecurity: FfiConverterRustBuffer<FfiSecurity> {
    override fun read(buf: ByteBuffer): FfiSecurity {
        return FfiSecurity(
            FfiConverterTypeFfiSecurityMode.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalTypeFfiRealityConfig.read(buf),
        )
    }

    override fun allocationSize(value: FfiSecurity) = (
            FfiConverterTypeFfiSecurityMode.allocationSize(value.`mode`) +
            FfiConverterOptionalString.allocationSize(value.`sni`) +
            FfiConverterSequenceString.allocationSize(value.`alpn`) +
            FfiConverterBoolean.allocationSize(value.`allowInsecure`) +
            FfiConverterOptionalString.allocationSize(value.`fingerprint`) +
            FfiConverterOptionalTypeFfiRealityConfig.allocationSize(value.`reality`)
    )

    override fun write(value: FfiSecurity, buf: ByteBuffer) {
            FfiConverterTypeFfiSecurityMode.write(value.`mode`, buf)
            FfiConverterOptionalString.write(value.`sni`, buf)
            FfiConverterSequenceString.write(value.`alpn`, buf)
            FfiConverterBoolean.write(value.`allowInsecure`, buf)
            FfiConverterOptionalString.write(value.`fingerprint`, buf)
            FfiConverterOptionalTypeFfiRealityConfig.write(value.`reality`, buf)
    }
}



/**
 * Transport-level parameters (ws path, grpc service name, …).
 */
data class FfiTransport (
    var `network`: FfiTransportNetwork?
    , 
    var `host`: kotlin.String?
    , 
    var `path`: kotlin.String?
    , 
    var `serviceName`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransport: FfiConverterRustBuffer<FfiTransport> {
    override fun read(buf: ByteBuffer): FfiTransport {
        return FfiTransport(
            FfiConverterOptionalTypeFfiTransportNetwork.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransport) = (
            FfiConverterOptionalTypeFfiTransportNetwork.allocationSize(value.`network`) +
            FfiConverterOptionalString.allocationSize(value.`host`) +
            FfiConverterOptionalString.allocationSize(value.`path`) +
            FfiConverterOptionalString.allocationSize(value.`serviceName`)
    )

    override fun write(value: FfiTransport, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiTransportNetwork.write(value.`network`, buf)
            FfiConverterOptionalString.write(value.`host`, buf)
            FfiConverterOptionalString.write(value.`path`, buf)
            FfiConverterOptionalString.write(value.`serviceName`, buf)
    }
}



/**
 * Per-tunnel knobs the platform wants reflected in the generated
 * Xray config. Mirrors `gmvpn_core::TunnelOptions`.
 */
data class FfiTunnelOptions (
    /**
     * Loopback or interface address the SOCKS inbound binds to.
     */
    var `socksListen`: kotlin.String
    , 
    /**
     * Local port for the SOCKS inbound.
     */
    var `socksPort`: kotlin.UShort
    , 
    /**
     * Xray log verbosity.
     */
    var `logLevel`: FfiLogLevel
    , 
    /**
     * DNS servers Xray uses while the tunnel is up. Empty list →
     * Xray default.
     */
    var `dnsServers`: List<kotlin.String>
    , 
    /**
     * Enable destination-override sniffing on the SOCKS inbound.
     */
    var `enableSniffing`: kotlin.Boolean
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTunnelOptions: FfiConverterRustBuffer<FfiTunnelOptions> {
    override fun read(buf: ByteBuffer): FfiTunnelOptions {
        return FfiTunnelOptions(
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterTypeFfiLogLevel.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: FfiTunnelOptions) = (
            FfiConverterString.allocationSize(value.`socksListen`) +
            FfiConverterUShort.allocationSize(value.`socksPort`) +
            FfiConverterTypeFfiLogLevel.allocationSize(value.`logLevel`) +
            FfiConverterSequenceString.allocationSize(value.`dnsServers`) +
            FfiConverterBoolean.allocationSize(value.`enableSniffing`)
    )

    override fun write(value: FfiTunnelOptions, buf: ByteBuffer) {
            FfiConverterString.write(value.`socksListen`, buf)
            FfiConverterUShort.write(value.`socksPort`, buf)
            FfiConverterTypeFfiLogLevel.write(value.`logLevel`, buf)
            FfiConverterSequenceString.write(value.`dnsServers`, buf)
            FfiConverterBoolean.write(value.`enableSniffing`, buf)
    }
}



/**
 * Output of a successful `decode_subscription_uris` call. Each
 * successful entry is a normalized URI string; clients can store
 * the URIs in their profile library and re-parse on demand.
 */
data class FfiUriDecodeOutput (
    var `uris`: List<kotlin.String>
    , 
    var `warnings`: List<FfiDecodeWarning>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiUriDecodeOutput: FfiConverterRustBuffer<FfiUriDecodeOutput> {
    override fun read(buf: ByteBuffer): FfiUriDecodeOutput {
        return FfiUriDecodeOutput(
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceTypeFfiDecodeWarning.read(buf),
        )
    }

    override fun allocationSize(value: FfiUriDecodeOutput) = (
            FfiConverterSequenceString.allocationSize(value.`uris`) +
            FfiConverterSequenceTypeFfiDecodeWarning.allocationSize(value.`warnings`)
    )

    override fun write(value: FfiUriDecodeOutput, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`uris`, buf)
            FfiConverterSequenceTypeFfiDecodeWarning.write(value.`warnings`, buf)
    }
}



/**
 * Authentication material, tagged by protocol. UUIDs are passed as
 * lowercase 36-char strings.
 */
sealed class FfiAuth {
    
    data class Vless(
        val `uuid`: kotlin.String, 
        val `flow`: kotlin.String?, 
        val `encryption`: kotlin.String?) : FfiAuth()
        
    {
        

        companion object
    }
    
    data class Vmess(
        val `uuid`: kotlin.String, 
        val `alterId`: kotlin.UShort, 
        val `security`: kotlin.String?) : FfiAuth()
        
    {
        

        companion object
    }
    
    data class Trojan(
        val `password`: kotlin.String) : FfiAuth()
        
    {
        

        companion object
    }
    
    data class Shadowsocks(
        val `method`: kotlin.String, 
        val `password`: kotlin.String) : FfiAuth()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiAuth : FfiConverterRustBuffer<FfiAuth>{
    override fun read(buf: ByteBuffer): FfiAuth {
        return when(buf.getInt()) {
            1 -> FfiAuth.Vless(
                FfiConverterString.read(buf),
                FfiConverterOptionalString.read(buf),
                FfiConverterOptionalString.read(buf),
                )
            2 -> FfiAuth.Vmess(
                FfiConverterString.read(buf),
                FfiConverterUShort.read(buf),
                FfiConverterOptionalString.read(buf),
                )
            3 -> FfiAuth.Trojan(
                FfiConverterString.read(buf),
                )
            4 -> FfiAuth.Shadowsocks(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FfiAuth) = when(value) {
        is FfiAuth.Vless -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`uuid`)
                + FfiConverterOptionalString.allocationSize(value.`flow`)
                + FfiConverterOptionalString.allocationSize(value.`encryption`)
            )
        }
        is FfiAuth.Vmess -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`uuid`)
                + FfiConverterUShort.allocationSize(value.`alterId`)
                + FfiConverterOptionalString.allocationSize(value.`security`)
            )
        }
        is FfiAuth.Trojan -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`password`)
            )
        }
        is FfiAuth.Shadowsocks -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`method`)
                + FfiConverterString.allocationSize(value.`password`)
            )
        }
    }

    override fun write(value: FfiAuth, buf: ByteBuffer) {
        when(value) {
            is FfiAuth.Vless -> {
                buf.putInt(1)
                FfiConverterString.write(value.`uuid`, buf)
                FfiConverterOptionalString.write(value.`flow`, buf)
                FfiConverterOptionalString.write(value.`encryption`, buf)
                Unit
            }
            is FfiAuth.Vmess -> {
                buf.putInt(2)
                FfiConverterString.write(value.`uuid`, buf)
                FfiConverterUShort.write(value.`alterId`, buf)
                FfiConverterOptionalString.write(value.`security`, buf)
                Unit
            }
            is FfiAuth.Trojan -> {
                buf.putInt(3)
                FfiConverterString.write(value.`password`, buf)
                Unit
            }
            is FfiAuth.Shadowsocks -> {
                buf.putInt(4)
                FfiConverterString.write(value.`method`, buf)
                FfiConverterString.write(value.`password`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





/**
 * Xray-core log verbosity passed to `build_xray_config`.
 */

enum class FfiLogLevel {
    
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    NONE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiLogLevel: FfiConverterRustBuffer<FfiLogLevel> {
    override fun read(buf: ByteBuffer) = try {
        FfiLogLevel.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiLogLevel) = 4UL

    override fun write(value: FfiLogLevel, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Wire protocol a profile speaks.
 */

enum class FfiProtocol {
    
    VLESS,
    VMESS,
    TROJAN,
    SHADOWSOCKS;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiProtocol: FfiConverterRustBuffer<FfiProtocol> {
    override fun read(buf: ByteBuffer) = try {
        FfiProtocol.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiProtocol) = 4UL

    override fun write(value: FfiProtocol, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * TLS mode applied to the transport.
 */

enum class FfiSecurityMode {
    
    NONE,
    TLS,
    REALITY;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiSecurityMode: FfiConverterRustBuffer<FfiSecurityMode> {
    override fun read(buf: ByteBuffer) = try {
        FfiSecurityMode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiSecurityMode) = 4UL

    override fun write(value: FfiSecurityMode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Wire format of a subscription response.
 */

enum class FfiSubscriptionFormat {
    
    /**
     * Plain text, one URI per line (`#` introduces a comment).
     */
    URI_LIST,
    /**
     * Base64 of a uri-list body.
     */
    BASE64_URI_LIST,
    /**
     * SIP008 JSON (Shadowsocks).
     */
    SIP008;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiSubscriptionFormat: FfiConverterRustBuffer<FfiSubscriptionFormat> {
    override fun read(buf: ByteBuffer) = try {
        FfiSubscriptionFormat.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiSubscriptionFormat) = 4UL

    override fun write(value: FfiSubscriptionFormat, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Transport network under the chosen protocol.
 */

enum class FfiTransportNetwork {
    
    TCP,
    WS,
    GRPC,
    HTTP2,
    QUIC,
    KCP,
    HTTPUPGRADE,
    SPLITHTTP;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiTransportNetwork: FfiConverterRustBuffer<FfiTransportNetwork> {
    override fun read(buf: ByteBuffer) = try {
        FfiTransportNetwork.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiTransportNetwork) = 4UL

    override fun write(value: FfiTransportNetwork, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







/**
 * Error variants returned across the FFI boundary.
 *
 * Every variant carries a textual `message` so the platform side can
 * surface the precise reason without reaching into the enum shape.
 */
sealed class GmvpnException(message: String): kotlin.Exception(message) {
        
        class InvalidUri(message: String) : GmvpnException(message)
        
        class UnsupportedProtocol(message: String) : GmvpnException(message)
        
        class MissingField(message: String) : GmvpnException(message)
        
        class InvalidValue(message: String) : GmvpnException(message)
        
        class Decode(message: String) : GmvpnException(message)
        
        class Serialization(message: String) : GmvpnException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<GmvpnException> {
        override fun lift(error_buf: RustBuffer.ByValue): GmvpnException = FfiConverterTypeGmvpnError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeGmvpnError : FfiConverterRustBuffer<GmvpnException> {
    override fun read(buf: ByteBuffer): GmvpnException {
        
            return when(buf.getInt()) {
            1 -> GmvpnException.InvalidUri(FfiConverterString.read(buf))
            2 -> GmvpnException.UnsupportedProtocol(FfiConverterString.read(buf))
            3 -> GmvpnException.MissingField(FfiConverterString.read(buf))
            4 -> GmvpnException.InvalidValue(FfiConverterString.read(buf))
            5 -> GmvpnException.Decode(FfiConverterString.read(buf))
            6 -> GmvpnException.Serialization(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: GmvpnException): ULong {
        return 4UL
    }

    override fun write(value: GmvpnException, buf: ByteBuffer) {
        when(value) {
            is GmvpnException.InvalidUri -> {
                buf.putInt(1)
                Unit
            }
            is GmvpnException.UnsupportedProtocol -> {
                buf.putInt(2)
                Unit
            }
            is GmvpnException.MissingField -> {
                buf.putInt(3)
                Unit
            }
            is GmvpnException.InvalidValue -> {
                buf.putInt(4)
                Unit
            }
            is GmvpnException.Decode -> {
                buf.putInt(5)
                Unit
            }
            is GmvpnException.Serialization -> {
                buf.putInt(6)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiRealityConfig: FfiConverterRustBuffer<FfiRealityConfig?> {
    override fun read(buf: ByteBuffer): FfiRealityConfig? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiRealityConfig.read(buf)
    }

    override fun allocationSize(value: FfiRealityConfig?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiRealityConfig.allocationSize(value)
        }
    }

    override fun write(value: FfiRealityConfig?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiRealityConfig.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiTransportNetwork: FfiConverterRustBuffer<FfiTransportNetwork?> {
    override fun read(buf: ByteBuffer): FfiTransportNetwork? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiTransportNetwork.read(buf)
    }

    override fun allocationSize(value: FfiTransportNetwork?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiTransportNetwork.allocationSize(value)
        }
    }

    override fun write(value: FfiTransportNetwork?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiTransportNetwork.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiDecodeWarning: FfiConverterRustBuffer<List<FfiDecodeWarning>> {
    override fun read(buf: ByteBuffer): List<FfiDecodeWarning> {
        val len = buf.getInt()
        return List<FfiDecodeWarning>(len) {
            FfiConverterTypeFfiDecodeWarning.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiDecodeWarning>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiDecodeWarning.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiDecodeWarning>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiDecodeWarning.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiProfile: FfiConverterRustBuffer<List<FfiProfile>> {
    override fun read(buf: ByteBuffer): List<FfiProfile> {
        val len = buf.getInt()
        return List<FfiProfile>(len) {
            FfiConverterTypeFfiProfile.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiProfile>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiProfile.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiProfile>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiProfile.write(it, buf)
        }
    }
}
        /**
         * Build the Xray-core JSON configuration for a profile and tunnel
         * options. Pass the returned string straight to the Go wrapper's
         * `Tunnel.Start(configJSON, tunFD)`.
         */
    @Throws(GmvpnException::class) fun `buildXrayConfig`(`profile`: FfiProfile, `options`: FfiTunnelOptions): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(GmvpnException) { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_build_xray_config(
    
        FfiConverterTypeFfiProfile.lower(`profile`),FfiConverterTypeFfiTunnelOptions.lower(`options`),_status)
}
    )
    }
    

        /**
         * Semantic version of `gmvpn-core`, surfaced in diagnostics views.
         */ fun `coreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_core_version(
    
        _status)
}
    )
    }
    

        /**
         * Decode a fetched subscription body. Partial failures surface as
         * entries in [`FfiDecodeOutput::warnings`]; the call itself only
         * fails on a fundamental problem with the body (non-utf8 uri list,
         * undecodable base64, malformed sip008 document).
         */
    @Throws(GmvpnException::class) fun `decodeSubscription`(`body`: kotlin.ByteArray, `format`: FfiSubscriptionFormat): FfiDecodeOutput {
            return FfiConverterTypeFfiDecodeOutput.lift(
    uniffiRustCallWithError(GmvpnException) { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_decode_subscription(
    
        FfiConverterByteArray.lower(`body`),FfiConverterTypeFfiSubscriptionFormat.lower(`format`),_status)
}
    )
    }
    

        /**
         * String-only counterpart of [`decode_subscription`]. Returns
         * reusable URI strings rather than fully-parsed profiles, so a
         * platform-side library can persist subscription contents as
         * strings and re-parse on demand.
         */
    @Throws(GmvpnException::class) fun `decodeSubscriptionUris`(`body`: kotlin.ByteArray, `format`: FfiSubscriptionFormat): FfiUriDecodeOutput {
            return FfiConverterTypeFfiUriDecodeOutput.lift(
    uniffiRustCallWithError(GmvpnException) { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_decode_subscription_uris(
    
        FfiConverterByteArray.lower(`body`),FfiConverterTypeFfiSubscriptionFormat.lower(`format`),_status)
}
    )
    }
    

        /**
         * Default tunnel options. Exposed so callers don't have to know our
         * defaults — only override what they need.
         */ fun `defaultTunnelOptions`(): FfiTunnelOptions {
            return FfiConverterTypeFfiTunnelOptions.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_default_tunnel_options(
    
        _status)
}
    )
    }
    

        /**
         * Parse any supported profile URI (vless / vmess / trojan / ss) into
         * a fully-typed profile record.
         */
    @Throws(GmvpnException::class) fun `parseProfileUri`(`uri`: kotlin.String): FfiProfile {
            return FfiConverterTypeFfiProfile.lift(
    uniffiRustCallWithError(GmvpnException) { _status ->
    UniffiLib.uniffi_gmvpn_ffi_fn_func_parse_profile_uri(
    
        FfiConverterString.lower(`uri`),_status)
}
    )
    }
    


