package com.gmvpn.client.diagnostics

import android.util.Log
import java.io.BufferedReader
import java.io.InputStreamReader
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Read the tail of logcat for the current process. Android since 4.1
 * restricts apps to seeing only their own log output, which is what we
 * want for a "diagnostics export" feature: the user gets the noise
 * generated by GMvpn (and only by GMvpn) without us asking for the
 * privileged READ_LOGS permission.
 */
object LogcatTail {

    private const val TAG = "LogcatTail"

    suspend fun read(maxLines: Int = 500): String = withContext(Dispatchers.IO) {
        try {
            val process = ProcessBuilder()
                .command("logcat", "-d", "-t", maxLines.toString(), "-v", "time")
                .redirectErrorStream(true)
                .start()
            val text = BufferedReader(InputStreamReader(process.inputStream)).use { it.readText() }
            process.waitFor()
            text
        } catch (e: Throwable) {
            Log.w(TAG, "logcat read failed", e)
            "(logcat read failed: ${e.message})"
        }
    }
}
