package com.gmvpn.client.diagnostics

import android.util.Log
import java.io.BufferedReader
import java.io.InputStreamReader
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Read the tail of logcat for the current process. Android since 4.1
 * restricts apps to seeing only their own log output, which is what we
 * want for a "diagnostics export" feature: the user gets the noise
 * generated by GMvpn (and only by GMvpn) without us asking for the
 * privileged READ_LOGS permission.
 *
 * As a defence-in-depth against a future Android version relaxing
 * that default, every line is matched against
 * `Process.myPid()` (logcat `-v threadtime` puts the PID in the
 * third whitespace-separated field) and foreign lines are dropped.
 * The dropped count is prefixed to the output as a one-line header
 * so the diagnostics blob makes the discrepancy visible — see
 * `docs/security-review-001.md` §3.
 */
object LogcatTail {

    private const val TAG = "LogcatTail"

    suspend fun read(maxLines: Int = 500): String = withContext(Dispatchers.IO) {
        val pid = android.os.Process.myPid()
        try {
            val process = ProcessBuilder()
                .command("logcat", "-d", "-t", maxLines.toString(), "-v", "threadtime")
                .redirectErrorStream(true)
                .start()
            val raw = BufferedReader(InputStreamReader(process.inputStream)).use { it.readText() }
            process.waitFor()
            assemble(raw, pid)
        } catch (e: Throwable) {
            Log.w(TAG, "logcat read failed", e)
            "(logcat read failed: ${e.message})"
        }
    }

    private fun assemble(raw: String, pid: Int): String {
        val lines = raw.split('\n')
        val result = filterByPid(lines, pid)
        val header = if (result.droppedCount > 0) {
            "[gmvpn] kept ${result.kept.size} lines; dropped " +
                "${result.droppedCount} foreign-pid lines\n"
        } else {
            ""
        }
        return header + result.kept.joinToString("\n")
    }

    /**
     * Pure-function pid filter for `logcat -v threadtime` output.
     * Lines that look like log entries (fourth field is the level
     * letter) are kept only when their PID column matches `pid`.
     * Anything that doesn't parse as a log line (separator banners,
     * blank lines, the trailing newline split) is kept verbatim so
     * the user still sees framing.
     */
    internal fun filterByPid(lines: List<String>, pid: Int): FilterResult {
        val pidStr = pid.toString()
        val kept = ArrayList<String>(lines.size)
        var dropped = 0
        for (line in lines) {
            val tokens = line.trimStart().split(WS_REGEX, limit = 5)
            if (!looksLikeThreadtimeLine(tokens)) {
                kept.add(line)
                continue
            }
            if (tokens[2] == pidStr) {
                kept.add(line)
            } else {
                dropped++
            }
        }
        return FilterResult(kept, dropped)
    }

    private fun looksLikeThreadtimeLine(tokens: List<String>): Boolean {
        // threadtime: <date> <time> <pid> <tid> <level> <tag>: <msg>
        if (tokens.size < 5) return false
        if (tokens[2].toIntOrNull() == null) return false
        if (tokens[3].toIntOrNull() == null) return false
        // Level is one of V D I W E F.
        return tokens[4].length >= 1 && tokens[4][0] in LEVELS
    }

    internal data class FilterResult(val kept: List<String>, val droppedCount: Int)

    private val WS_REGEX = Regex("\\s+")
    private val LEVELS = setOf('V', 'D', 'I', 'W', 'E', 'F')
}
